### ISSUE TITLE
TypeError: Cannot read property 'localSetup' of undefined

### ISSUE THREAD

**Issue by iamShantanu101** [guymorita/Mosaic-Films---Recommendation-Engine-Demo#24]
I am getting an error when I try to  run : 
node node-server.js

Here is the description of the error : 
/Mosaic-Films---Recommendation-Engine-Demo/sampleContent/starter.js:11
  if (raccoon.config.localSetup === true){
                    ^

TypeError: Cannot read property 'localSetup' of undefined
    at Object.exports.starter (/Mosaic-Films---Recommendation-Engine-Demo/sampleContent/starter.js:11:21)
    at Object.<anonymous> (/Mosaic-Films---Recommendation-Engine-Demo/node-server.js:5:53)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by AnasMostefaoui** [comment]
i fixed that issue, buy installing the last version of "raccoon": "^0.2.3"

**Comment by iamShantanu101** [comment]
Thanks it was solved, but here is another error
remote mongo
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: failed to connect to [undefined:27017]
    at null.<anonymous> (/Mosaic-Films---Recommendation-Engine-Demo/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:540:25)
    at emitThree (events.js:97:13)
    at emit (events.js:175:7)
    at null.<anonymous> (/Mosaic-Films---Recommendation-Engine-Demo/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/Mosaic-Films---Recommendation-Engine-Demo/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:478:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at connectErrorNT (net.js:996:8)

**Comment by guymorita** [comment]
@iamShantanu101  @AnasMostefaoui  Hey, I just fixed the demo. It will work with all local dbs. Otherwise you can customize the URL's and ports yourself. Enjoy!
