### ISSUE TITLE
Error after input of username on homepage

### ISSUE THREAD

**Issue by vavarun** [guymorita/Mosaic-Films---Recommendation-Engine-Demo#25]
I have followed all the steps as mentioned in your readme and get the following error. If you could kindly assist me . Gracias !

``` 
Unhandled rejection ReferenceError: client is not defined
    at Object.allWatchedFor (/Users/Varun/Desktop/recc-engine/Mosaic-Films---Recommendation-Engine-Demo/node_modules/raccoon/lib/stat.js:79:5)
    at /Users/Varun/Desktop/recc-engine/Mosaic-Films---Recommendation-Engine-Demo/lib/starter.js:23:20
at tryCatcher (/Users/Varun/Desktop/recc-engine/Mosaic-Films---Recommendation-Engine-Demo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Varun/Desktop/recc-engine/Mosaic-Films---Recommendation-Engine-Demo/node_modules/bluebird/js/release/promise.js:507:35)
    at Promise._settlePromise (/Users/Varun/Desktop/recc-engine/Mosaic-Films---Recommendation-Engine-Demo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/Varun/Desktop/recc-engine/Mosaic-Films---Recommendation-Engine-Demo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/Varun/Desktop/recc-engine/Mosaic-Films---Recommendation-Engine-Demo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/Varun/Desktop/recc-engine/Mosaic-Films---Recommendation-Engine-Demo/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/Users/Varun/Desktop/recc-engine/Mosaic-Films---Recommendation-Engine-Demo/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/Varun/Desktop/recc-engine/Mosaic-Films---Recommendation-Engine-Demo/node_modules/bluebird/js/release/promise_array.js:143:14)
    at PromiseArray._iterate (/Users/Varun/Desktop/recc-engine/Mosaic-Films---Recommendation-Engine-Demo/node_modules/bluebird/js/release/promise_array.js:113:31)
    at PromiseArray.init [as _init] (/Users/Varun/Desktop/recc-engine/Mosaic-Films---Recommendation-Engine-Demo/node_modules/bluebird/js/release/promise_array.js:77:10)
    at Promise._settlePromise (/Users/Varun/Desktop/recc-engine/Mosaic-Films---Recommendation-Engine-Demo/node_modules/bluebird/js/release/promise.js:564:21)
    at Promise._settlePromise0 (/Users/Varun/Desktop/recc-engine/Mosaic-Films---Recommendation-Engine-Demo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/Varun/Desktop/recc-engine/Mosaic-Films---Recommendation-Engine-Demo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/Varun/Desktop/recc-engine/Mosaic-Films---Recommendation-Engine-Demo/node_modules/bluebird/js/release/promise.js:636:18) 
```

**Comment by guymorita** [comment]
@vavarun Hey, thanks for the report. Can you try again? I just updated NPM for raccoon to use the new version. 0.2.5. Lemme know if it's still a problem. Thanks.

**Comment by hiraghuak** [comment]
Hi please help me with this error, after runing this node lib/importMovies.js 

`Unhandled rejection TypeError: Movie.build is not a function
    at insertMovie (/Users/apple/Public/bharath/raghu/BG/test/Mosaic-Films---Recommendation-Engine-Demo/lib/importMovies.js:19:25)
    at /Users/apple/Public/bharath/raghu/BG/test/Mosaic-Films---Recommendation-Engine-Demo/lib/importMovies.js:48:7
    at tryCatcher (/Users/apple/Public/bharath/raghu/BG/test/Mosaic-Films---Recommendation-Engine-Demo/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/apple/Public/bharath/raghu/BG/test/Mosaic-Films---Recommendation-Engine-Demo/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/apple/Public/bharath/raghu/BG/test/Mosaic-Films---Recommendation-Engine-Demo/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/apple/Public/bharath/raghu/BG/test/Mosaic-Films---Recommendation-Engine-Demo/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/apple/Public/bharath/raghu/BG/test/Mosaic-Films---Recommendation-Engine-Demo/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/Users/apple/Public/bharath/raghu/BG/test/Mosaic-Films---Recommendation-Engine-Demo/node_modules/sequelize/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/apple/Public/bharath/raghu/BG/test/Mosaic-Films---Recommendation-Engine-Demo/node_modules/sequelize/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/apple/Public/bharath/raghu/BG/test/Mosaic-Films---Recommendation-Engine-Demo/node_modules/sequelize/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/apple/Public/bharath/raghu/BG/test/Mosaic-Films---Recommendation-Engine-Demo/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)`
